##############################################
#  ░▒█▀▀▄░█▀▀░▀█▀░█░▒█░█▀▀▄░█▀▀▄░▒█▀▄▀█░█▀▀  #
#  ░▒█▄▄▀░█▀▀░░█░░█░▒█░█▄▄▀░█░▒█░▒█▒█▒█░█▀▀  #
#  ░▒█░▒█░▀▀▀░░▀░░░▀▀▀░▀░▀▀░▀░░▀░▒█░░▒█░▀▀▀  #
##############################################

# This file handles the configuration for the ReturnMe Minecraft plugin.
# Plugin created by Triassic.


# Should players need a permission to be sent to their last location?
# If enabled, players will require the "returnme.use" permission to be sent to their last location.
require-permission: false

# A list of players to exempt from being sent to their last location.
# Bypasses the "returnme.use" permission.
exempted-players:
  - Player1
  - Player2

# The server where players log in.
# This would typically be the "unloggedUserServer" from AuthMeBungee.
login-server: "login"

# Players who log in and do not have a previous server set or
# the server that was set is offline, will be connected to this server.
default-server: "spawn"

# Toggle whether your server stats are sent to https://bstats.org.
# All data collected is fully anonymous and by setting this option to false you can opt-out.
toggle-metrics: true


version: ${project.version} # DO NOT MODIFY.